.TH AUTO-DISCOVER 1 "March 31, 2016"
.SH NAME
snimpy \- network auto-discovery tool with Python
.SH SYNOPSIS
.B auto-discover
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B snimpy
command.
.PP
\fBauto-discover\fP is a Python-based tool for querying the network to take inventory of servers and what services they are running.
.PP
\fBsnimpy\fP can be used either interactively through its console
(derived from Python own console or from IPython if available) or by
writing \fBsnimpy\fP scripts which are just Python scripts with some global
variables available.
.SH OPTIONS
\fBsnimpy\fP does not take any option. If you launch it without any
argument, you will get the interactive console. Otherwise, the first
argument is the name of a script to be executed and the remaining
arguments are the arguments for this script.

.SH SEE ALSO

.nf
https://github.com/thomasvincent/auto-discover
.fi

.SH AUTHOR
thomas vincent <thomasvincent@gmail.com>