name: Dependabot Auto-Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.event.pull_request.draft == false
    steps:
      - name: Check if PR is from Dependabot
        id: dependabot-check
        run: |
          echo "This PR is from Dependabot"
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

      - name: Wait for status checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "Python CI"
          ref: ${{ github.event.pull_request.head.sha }}
          timeoutSeconds: 1800

      - name: Auto-merge minor and patch updates
        if: |
          steps.wait-for-checks.outputs.conclusion == 'success' &&
          (contains(github.event.pull_request.title, 'bump') || 
           contains(github.event.pull_request.title, 'update') ||
           contains(github.event.pull_request.title, 'Update'))
        run: |
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for major updates with approval
        if: |
          steps.wait-for-checks.outputs.conclusion == 'success' &&
          (contains(github.event.pull_request.title, 'major') ||
           contains(github.event.pull_request.title, 'Major'))
        run: |
          echo "Major update detected - enabling auto-merge but requires manual approval"
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}" || echo "Auto-merge enabled, waiting for approval"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}